### ISSUE TITLE
Find out more link goes nowhere

### ISSUE THREAD

**Issue by opdavies** [nwdrupal/nwdrupalwebsite#11]
The "Find out more" link on the homepage links to http://nwdrupal.org.uk, which is the same page that I'm currently on.

<img width="646" alt="screen shot 2016-02-18 at 08 10 52" src="https://cloud.githubusercontent.com/assets/339813/13137191/4392916e-d617-11e5-93da-6066f0458f98.png">

**Comment by mikebell** [comment]
I've commented out the html for the time being until we have some content that it can point to.

**Comment by opdavies** [comment]
:+1:
