### ISSUE TITLE
Meetup RSVPs not reporting correctly

### ISSUE THREAD

**Issue by mikebell** [nwdrupal/nwdrupalwebsite#4]
http://nwdrupal.org.uk/event/2016/02/09/north-west-drupal-usergroup-meetup-february-2016 << shows 2

http://www.meetup.com/nwdrupal/events/227567774/ << shows 8

**Comment by philipnorton42** [comment]
The meetup update hadn't been run. I've run it now so the numbers are good but I'll need to get a cron task running for that :)

**Comment by philipnorton42** [comment]
Done! :)
